<center>
  <a href="MLSD-05-FeatureSelection-B.ipynb" target="_self">Feature Selection B</a> | <a href="./">Content Page</a> | <a href="MLSD-06-MachineLearningErrors.ipynb">Machine Learning Errors</a>
</center>

# <center>FEATURE SELECTION: EXERCISE 1</center>

<center><b>Copyright &copy 2023 by DR DANNY POO</b><br> e:dannypoo@nus.edu.sg<br> w:drdannypoo.com</center><br>

# Diabetes
You are given the Pima Indians Diabetes dataset  ``./data/diabetes/diabetes.csv``.

**Description of attributes:**<br>
For Each Attribute: (all numeric-valued)
   1. Number of times pregnant
   2. Plasma glucose concentration a 2 hours in an oral glucose tolerance test
   3. Diastolic blood pressure (mm Hg)
   4. Triceps skin fold thickness (mm)
   5. 2-Hour serum insulin (mu U/ml)
   6. Body mass index (weight in kg/(height in m)^2)
   7. Diabetes pedigree function
   8. Age (years)
   9. Class variable (0 or 1)

<b>Objective: To determine important features in dataset for classification.</b>

Skeletal code is provided here. Complete those indicated `write code here`.

# Read in and Explore Data Set

In [1]:
# Import libraries
# write code here




In [2]:
# Read in the dataset. Preview the dataset by printing the first 5 rows of dataframe.
# write code here
df = pd.read_csv('./data/diabetes/diabetes.csv')
df.head()

preg_count  glucose_concentration  blood_pressure  skin_thickness  \
0           6                    148              72              35   
1           1                     85              66              29   
2           8                    183              64               0   
3           1                     89              66              23   
4           0                    137              40              35   

   serum_insulin   bmi  pedigree_function  age  class  
0              0  33.6              0.627   50      1  
1              0  26.6              0.351   31      0  
2              0  23.3              0.672   32      1  
3             94  28.1              0.167   21      0  
4            168  43.1              2.288   33      1

In [3]:
# Create features and target
# write code here




In [4]:
# Print X shape and first 5 rows
print(X.shape, "\n", X[0:5])

(768, 8) 
 [[6.000e+00 1.480e+02 7.200e+01 3.500e+01 0.000e+00 3.360e+01 6.270e-01
  5.000e+01]
 [1.000e+00 8.500e+01 6.600e+01 2.900e+01 0.000e+00 2.660e+01 3.510e-01
  3.100e+01]
 [8.000e+00 1.830e+02 6.400e+01 0.000e+00 0.000e+00 2.330e+01 6.720e-01
  3.200e+01]
 [1.000e+00 8.900e+01 6.600e+01 2.300e+01 9.400e+01 2.810e+01 1.670e-01
  2.100e+01]
 [0.000e+00 1.370e+02 4.000e+01 3.500e+01 1.680e+02 4.310e+01 2.288e+00
  3.300e+01]]


In [5]:
# Print y shape and first 5 rows
print(y.shape, "\n", y[0:5])

(768,) 
 [1. 0. 1. 0. 1.]


# Univariate Selection

In [6]:
# Import libraries
# To use sklearn.feature_selection.SelectKBest and f_classif() function to select the 4 best features
# write code here




In [7]:
# To select 4 best features
select = SelectKBest(score_func=f_classif, k=4)

In [8]:
# Fit it and assign the fit to variable 'best'
# write code here



In [9]:
# Summarize scores
np.set_printoptions(precision=3)
print(best.scores_)

[ 39.67  213.162   3.257   4.304  13.281  71.772  23.871  46.141]


In [10]:
# Select the 4 features with the highest scores
# write code here



**Observations**
- Scores for each of the 8 attributes are listed.
- Those attributes with the highest scores are with indexes 0(preg_count), 1(glucose_concentration), 5(bmi), and 7(age).

In [11]:
# Summarize selected features
print(features[0:5,:])

[[  6.  148.   33.6  50. ]
 [  1.   85.   26.6  31. ]
 [  8.  183.   23.3  32. ]
 [  1.   89.   28.1  21. ]
 [  0.  137.   43.1  33. ]]


# Feature Importance

In [12]:
# Import libraries
from sklearn.ensemble import ExtraTreesClassifier

In [13]:
# To use ExtraTreesClassifier to estimate the importance of features
# write code here





print(model.feature_importances_)  

[0.106 0.247 0.094 0.075 0.072 0.142 0.114 0.151]


**Observations**
- Importance score for each of the 8 attributes are listed where the larger the score the more important the attribute.
- The important attributes are with indexes 1(glucose_concentration), 5(bmi), and 7(age).

<center>
  <a href="MLSD-05-FeatureSelection-B.ipynb" target="_self">Feature Selection B</a> | <a href="./">Content Page</a> | <a href="MLSD-06-MachineLearningErrors.ipynb">Machine Learning Errors</a>
</center>