<center>
  <a href="MLSD-02-DataPreprocessing-E.ipynb" target="_self">Data Preprocessing E</a> | <a href="./">Content Page</a> | <a href="MLSD-03-DetectingAnomalies-A.ipynb">Detecting Anomalies A</a>
</center>

# <center>DATA PREPROCESSING: EXERCISE 1</center>

<center><b>Copyright &copy 2023 by DR DANNY POO</b><br> e:dannypoo@nus.edu.sg<br> w:drdannypoo.com</center><br>

# Graduate Dataset
<b>Dataset</b>: Graduate data set.<br>
<b>Tasks</b>: 
- To read in and explore data set.
- To fill missing data with mean values.
- To encode all categorical labels to column vectors with binary values.
- To split dataset.
- To rescale features.

## Read in and Explore Data Set

In [15]:
# Import libraries
# Write code here

import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from sklearn.impute import SimpleImputer


In [3]:
# Read in data
df = pd.read_csv('./data/graduate/data.csv')

In [4]:
# Examine data format
# Write code here
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Age       5 non-null      float64
 1   Income    5 non-null      float64
 2   Graduate  6 non-null      object 
dtypes: float64(2), object(1)
memory usage: 272.0+ bytes


In [5]:
# Print first 5 rows
# Write code here
df.head()



Age   Income Graduate
0  24.0  35000.0       no
1  26.0  48000.0       no
2   NaN  54000.0      yes
3  40.0  61000.0      yes
4  50.0      NaN       no

In [27]:
# Prepare X and y
# Write code here
X = df[['Age','Income']].values
y = df['Graduate'].values



In [18]:
# Print X
print(X)

[[2.4e+01 3.5e+04]
 [2.6e+01 4.8e+04]
 [    nan 5.4e+04]
 [4.0e+01 6.1e+04]
 [5.0e+01     nan]
 [3.5e+01 5.0e+04]]


In [14]:
# Print y
print(y)

[['no']
 ['no']
 ['yes']
 ['yes']
 ['no']
 ['yes']]


## Fill Missing Data with Mean Values

In [31]:
# Import class SimpleImputer from impute model in sklearn
# Write code here



# Create object of SimpleImputer class
# Write code here
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')

imp_mean.fit(X[:,0:2])



# Replace the missing value using transform method
# Write code here
X = imp_mean.transform(X)


print(X)

[[2.40e+01 3.50e+04]
 [2.60e+01 4.80e+04]
 [3.50e+01 5.40e+04]
 [4.00e+01 6.10e+04]
 [5.00e+01 4.96e+04]
 [3.50e+01 5.00e+04]]


**Observations**:
- Empty cells are now replaced with the mean of the column values.

## Encode Categorical Values

In [28]:
# Encode dependent variable y
# Write code here
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder() 
y = le.fit_transform(y)

print(y)

[0 0 1 1 0 1]


## Split Dataset into Training and Test Sets

In [32]:
# Import libraries
# Write code here
from sklearn.model_selection import train_test_split


# Split dataset
# Write code here
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,random_state= 1)



In [33]:
# Print
print("\nX_train\n", X_train)
print("\nX_test\n", X_test)
print("\ny_train\n", y_train)
print("\ny_test\n", y_test)


X_train
 [[5.00e+01 4.96e+04]
 [2.40e+01 3.50e+04]
 [4.00e+01 6.10e+04]
 [3.50e+01 5.00e+04]]

X_test
 [[3.5e+01 5.4e+04]
 [2.6e+01 4.8e+04]]

y_train
 [0 0 1 1]

y_test
 [1 0]


## Rescale Features

In [35]:
# Import libraries
# Write code here
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()




In [38]:
# Rescale X
# Write code here
rescaledX = scaler.fit_transform(X)



In [39]:
# Summarize transformed data
# Write code here



print(rescaledX[:,:])

[[-1.26735736 -1.8713848 ]
 [-1.03692875 -0.20508327]
 [ 0.          0.56397898]
 [ 0.57607153  1.46121826]
 [ 1.72821459  0.        ]
 [ 0.          0.05127082]]


**Observations**:
- It does not matter whether to scale encoded categorical data.
- It is up to you.

<center>
  <a href="MLSD-02-DataPreprocessing-E.ipynb" target="_self">Data Preprocessing E</a> | <a href="./">Content Page</a> | <a href="MLSD-03-DetectingAnomalies-A.ipynb">Detecting Anomalies A</a>
</center>